### ISSUE TITLE
Change: Separate tests into unit and integration

### ISSUE THREAD

**Issue by winterhotlatte** [cpuabuse/node-system#31]
## Description

Currently all tests are stored in several files in an unstructured manner, so need to structure them.

## Expected

All tests are separated into individual files stored in respective `unit`, `integration` and `data` folders.

## Actual

All tests are grouped by the file they test.

## Goals

- [x] Outline the criteria
- [x] Sort tests by criteria
- [x] Separate tests to new files
- [x] Make sure all new files have appropriate headers

**Comment by yanocv** [comment]
- 971141f5a666e9ffc8a89b150ed4bc18a5849456
- b37397d4738dd8875f82e6340eaed1e4c00385d6
- 0c0d72e7e555afa452a2f096c60c35855e20d9ff
- 014353ad1103f04772c9b48ba5bed6c87dd0a720

**Comment by yanocv** [comment]
Complete.
